package database

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
	"github.com/canonical/microcluster/cluster"
)

var _ = api.ServerEnvironment{}

var coreSiteTokenObjects = cluster.RegisterStmt(`
SELECT core_site_tokens.site_name, core_site_tokens.id, core_site_tokens.secret, core_site_tokens.expiry, core_site_tokens.created_at
  FROM core_site_tokens
  ORDER BY core_site_tokens.site_name
`)

var coreSiteTokenObjectsBySiteName = cluster.RegisterStmt(`
SELECT core_site_tokens.site_name, core_site_tokens.id, core_site_tokens.secret, core_site_tokens.expiry, core_site_tokens.created_at
  FROM core_site_tokens
  WHERE ( core_site_tokens.site_name = ? )
  ORDER BY core_site_tokens.site_name
`)

var coreSiteTokenID = cluster.RegisterStmt(`
SELECT core_site_tokens.id FROM core_site_tokens
  WHERE core_site_tokens.site_name = ?
`)

var coreSiteTokenCreate = cluster.RegisterStmt(`
INSERT INTO core_site_tokens (site_name, secret, expiry, created_at)
  VALUES (?, ?, ?, ?)
`)

var coreSiteTokenDeleteBySiteName = cluster.RegisterStmt(`
DELETE FROM core_site_tokens WHERE site_name = ?
`)

var coreSiteTokenUpdate = cluster.RegisterStmt(`
UPDATE core_site_tokens
  SET site_name = ?, secret = ?, expiry = ?, created_at = ?
 WHERE id = ?
`)

// coreSiteTokenColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the CoreSiteToken entity.
func coreSiteTokenColumns() string {
	return "cores_sites_tokens.site_name, cores_sites_tokens.id, cores_sites_tokens.secret, cores_sites_tokens.expiry, cores_sites_tokens.created_at"
}

// getCoreSiteTokens can be used to run handwritten sql.Stmts to return a slice of objects.
func getCoreSiteTokens(ctx context.Context, stmt *sql.Stmt, args ...any) ([]CoreSiteToken, error) {
	objects := make([]CoreSiteToken, 0)

	dest := func(scan func(dest ...any) error) error {
		c := CoreSiteToken{}
		err := scan(&c.SiteName, &c.ID, &c.Secret, &c.Expiry, &c.CreatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, c)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_sites_tokens\" table: %w", err)
	}

	return objects, nil
}

// getCoreSiteTokensRaw can be used to run handwritten query strings to return a slice of objects.
func getCoreSiteTokensRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]CoreSiteToken, error) {
	objects := make([]CoreSiteToken, 0)

	dest := func(scan func(dest ...any) error) error {
		c := CoreSiteToken{}
		err := scan(&c.SiteName, &c.ID, &c.Secret, &c.Expiry, &c.CreatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, c)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_sites_tokens\" table: %w", err)
	}

	return objects, nil
}

// GetCoreSiteTokens returns all available core_site_tokens.
// generator: core_site_token GetMany
func GetCoreSiteTokens(ctx context.Context, tx *sql.Tx, filters ...CoreSiteTokenFilter) ([]CoreSiteToken, error) {
	var err error

	// Result slice.
	objects := make([]CoreSiteToken, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = cluster.Stmt(tx, coreSiteTokenObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"coreSiteTokenObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.SiteName != nil {
			args = append(args, []any{filter.SiteName}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, coreSiteTokenObjectsBySiteName)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"coreSiteTokenObjectsBySiteName\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(coreSiteTokenObjectsBySiteName)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"coreSiteTokenObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.SiteName == nil {
			return nil, fmt.Errorf("Cannot filter on empty CoreSiteTokenFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getCoreSiteTokens(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getCoreSiteTokensRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_sites_tokens\" table: %w", err)
	}

	return objects, nil
}

// GetCoreSiteToken returns the core_site_token with the given key.
// generator: core_site_token GetOne
func GetCoreSiteToken(ctx context.Context, tx *sql.Tx, siteName string) (*CoreSiteToken, error) {
	filter := CoreSiteTokenFilter{}
	filter.SiteName = &siteName

	objects, err := GetCoreSiteTokens(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_sites_tokens\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "CoreSiteToken not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"cores_sites_tokens\" entry matches")
	}
}

// GetCoreSiteTokenID return the ID of the core_site_token with the given key.
// generator: core_site_token ID
func GetCoreSiteTokenID(ctx context.Context, tx *sql.Tx, siteName string) (int64, error) {
	stmt, err := cluster.Stmt(tx, coreSiteTokenID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"coreSiteTokenID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, siteName)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "CoreSiteToken not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"cores_sites_tokens\" ID: %w", err)
	}

	return id, nil
}

// CoreSiteTokenExists checks if a core_site_token with the given key exists.
// generator: core_site_token Exists
func CoreSiteTokenExists(ctx context.Context, tx *sql.Tx, siteName string) (bool, error) {
	_, err := GetCoreSiteTokenID(ctx, tx, siteName)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateCoreSiteToken adds a new core_site_token to the database.
// generator: core_site_token Create
func CreateCoreSiteToken(ctx context.Context, tx *sql.Tx, object CoreSiteToken) (int64, error) {
	// Check if a core_site_token with the same key exists.
	exists, err := CoreSiteTokenExists(ctx, tx, object.SiteName)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"cores_sites_tokens\" entry already exists")
	}

	args := make([]any, 4)

	// Populate the statement arguments.
	args[0] = object.SiteName
	args[1] = object.Secret
	args[2] = object.Expiry
	args[3] = object.CreatedAt

	// Prepared statement to use.
	stmt, err := cluster.Stmt(tx, coreSiteTokenCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"coreSiteTokenCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"cores_sites_tokens\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"cores_sites_tokens\" entry ID: %w", err)
	}

	return id, nil
}

// DeleteCoreSiteToken deletes the core_site_token matching the given key parameters.
// generator: core_site_token DeleteOne-by-SiteName
func DeleteCoreSiteToken(ctx context.Context, tx *sql.Tx, siteName string) error {
	stmt, err := cluster.Stmt(tx, coreSiteTokenDeleteBySiteName)
	if err != nil {
		return fmt.Errorf("Failed to get \"coreSiteTokenDeleteBySiteName\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(siteName)
	if err != nil {
		return fmt.Errorf("Delete \"cores_sites_tokens\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "CoreSiteToken not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d CoreSiteToken rows instead of 1", n)
	}

	return nil
}

// UpdateCoreSiteToken updates the core_site_token matching the given key parameters.
// generator: core_site_token Update
func UpdateCoreSiteToken(ctx context.Context, tx *sql.Tx, siteName string, object CoreSiteToken) error {
	id, err := GetCoreSiteTokenID(ctx, tx, siteName)
	if err != nil {
		return err
	}

	stmt, err := cluster.Stmt(tx, coreSiteTokenUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"coreSiteTokenUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.SiteName, object.Secret, object.Expiry, object.CreatedAt, id)
	if err != nil {
		return fmt.Errorf("Update \"cores_sites_tokens\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}
