package database

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
	"github.com/canonical/microcluster/cluster"
)

var _ = api.ServerEnvironment{}

var managerConfigObjects = cluster.RegisterStmt(`
SELECT manager_configs.key, manager_configs.id, manager_configs.value
  FROM manager_configs
  ORDER BY manager_configs.key
`)

var managerConfigObjectsByKey = cluster.RegisterStmt(`
SELECT manager_configs.key, manager_configs.id, manager_configs.value
  FROM manager_configs
  WHERE ( manager_configs.key = ? )
  ORDER BY manager_configs.key
`)

var managerConfigID = cluster.RegisterStmt(`
SELECT manager_configs.id FROM manager_configs
  WHERE manager_configs.key = ?
`)

var managerConfigCreate = cluster.RegisterStmt(`
INSERT INTO manager_configs (key, value)
  VALUES (?, ?)
`)

var managerConfigDeleteByKey = cluster.RegisterStmt(`
DELETE FROM manager_configs WHERE key = ?
`)

var managerConfigUpdate = cluster.RegisterStmt(`
UPDATE manager_configs
  SET key = ?, value = ?
 WHERE id = ?
`)

// managerConfigColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the ManagerConfig entity.
func managerConfigColumns() string {
	return "manager_configs.key, manager_configs.id, manager_configs.value"
}

// getManagerConfig can be used to run handwritten sql.Stmts to return a slice of objects.
func getManagerConfig(ctx context.Context, stmt *sql.Stmt, args ...any) ([]ManagerConfig, error) {
	objects := make([]ManagerConfig, 0)

	dest := func(scan func(dest ...any) error) error {
		m := ManagerConfig{}
		err := scan(&m.Key, &m.ID, &m.Value)
		if err != nil {
			return err
		}

		objects = append(objects, m)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"manager_configs\" table: %w", err)
	}

	return objects, nil
}

// getManagerConfigRaw can be used to run handwritten query strings to return a slice of objects.
func getManagerConfigRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]ManagerConfig, error) {
	objects := make([]ManagerConfig, 0)

	dest := func(scan func(dest ...any) error) error {
		m := ManagerConfig{}
		err := scan(&m.Key, &m.ID, &m.Value)
		if err != nil {
			return err
		}

		objects = append(objects, m)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"manager_configs\" table: %w", err)
	}

	return objects, nil
}

// GetManagerConfig returns all available manager_config.
// generator: manager_config GetMany
func GetManagerConfig(ctx context.Context, tx *sql.Tx, filters ...ManagerConfigFilter) ([]ManagerConfig, error) {
	var err error

	// Result slice.
	objects := make([]ManagerConfig, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = cluster.Stmt(tx, managerConfigObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"managerConfigObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.Key != nil {
			args = append(args, []any{filter.Key}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, managerConfigObjectsByKey)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"managerConfigObjectsByKey\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(managerConfigObjectsByKey)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"managerConfigObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Key == nil {
			return nil, fmt.Errorf("Cannot filter on empty ManagerConfigFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getManagerConfig(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getManagerConfigRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"manager_configs\" table: %w", err)
	}

	return objects, nil
}

// GetManagerConfigID return the ID of the manager_config with the given key.
// generator: manager_config ID
func GetManagerConfigID(ctx context.Context, tx *sql.Tx, key string) (int64, error) {
	stmt, err := cluster.Stmt(tx, managerConfigID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"managerConfigID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, key)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "ManagerConfig not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"manager_configs\" ID: %w", err)
	}

	return id, nil
}

// ManagerConfigExists checks if a manager_config with the given key exists.
// generator: manager_config Exists
func ManagerConfigExists(ctx context.Context, tx *sql.Tx, key string) (bool, error) {
	_, err := GetManagerConfigID(ctx, tx, key)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateManagerConfig adds a new manager_config to the database.
// generator: manager_config Create
func CreateManagerConfig(ctx context.Context, tx *sql.Tx, object ManagerConfig) (int64, error) {
	// Check if a manager_config with the same key exists.
	exists, err := ManagerConfigExists(ctx, tx, object.Key)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"manager_configs\" entry already exists")
	}

	args := make([]any, 2)

	// Populate the statement arguments.
	args[0] = object.Key
	args[1] = object.Value

	// Prepared statement to use.
	stmt, err := cluster.Stmt(tx, managerConfigCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"managerConfigCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"manager_configs\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"manager_configs\" entry ID: %w", err)
	}

	return id, nil
}

// DeleteManagerConfig deletes the manager_config matching the given key parameters.
// generator: manager_config DeleteOne-by-Key
func DeleteManagerConfig(ctx context.Context, tx *sql.Tx, key string) error {
	stmt, err := cluster.Stmt(tx, managerConfigDeleteByKey)
	if err != nil {
		return fmt.Errorf("Failed to get \"managerConfigDeleteByKey\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(key)
	if err != nil {
		return fmt.Errorf("Delete \"manager_configs\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "ManagerConfig not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d ManagerConfig rows instead of 1", n)
	}

	return nil
}

// UpdateManagerConfig updates the manager_config matching the given key parameters.
// generator: manager_config Update
func UpdateManagerConfig(ctx context.Context, tx *sql.Tx, key string, object ManagerConfig) error {
	id, err := GetManagerConfigID(ctx, tx, key)
	if err != nil {
		return err
	}

	stmt, err := cluster.Stmt(tx, managerConfigUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"managerConfigUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.Key, object.Value, id)
	if err != nil {
		return fmt.Errorf("Update \"manager_configs\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}
