package database

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
	"github.com/canonical/microcluster/v2/cluster"
)

var _ = api.ServerEnvironment{}

var managerMemberConfigObjects = cluster.RegisterStmt(`
SELECT manager_member_configs.target, manager_member_configs.id, manager_member_configs.https_address, manager_member_configs.external_address
  FROM manager_member_configs
  ORDER BY manager_member_configs.target
`)

var managerMemberConfigObjectsByTarget = cluster.RegisterStmt(`
SELECT manager_member_configs.target, manager_member_configs.id, manager_member_configs.https_address, manager_member_configs.external_address
  FROM manager_member_configs
  WHERE ( manager_member_configs.target = ? )
  ORDER BY manager_member_configs.target
`)

var managerMemberConfigID = cluster.RegisterStmt(`
SELECT manager_member_configs.id FROM manager_member_configs
  WHERE manager_member_configs.target = ?
`)

var managerMemberConfigCreate = cluster.RegisterStmt(`
INSERT INTO manager_member_configs (target, https_address, external_address)
  VALUES (?, ?, ?)
`)

var managerMemberConfigDeleteByTarget = cluster.RegisterStmt(`
DELETE FROM manager_member_configs WHERE target = ?
`)

var managerMemberConfigUpdate = cluster.RegisterStmt(`
UPDATE manager_member_configs
  SET target = ?, https_address = ?, external_address = ?
 WHERE id = ?
`)

// managerMemberConfigColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the ManagerMemberConfig entity.
func managerMemberConfigColumns() string {
	return "managers_members_config.target, managers_members_config.id, managers_members_config.https_address, managers_members_config.external_address"
}

// getManagerMemberConfig can be used to run handwritten sql.Stmts to return a slice of objects.
func getManagerMemberConfig(ctx context.Context, stmt *sql.Stmt, args ...any) ([]ManagerMemberConfig, error) {
	objects := make([]ManagerMemberConfig, 0)

	dest := func(scan func(dest ...any) error) error {
		m := ManagerMemberConfig{}
		err := scan(&m.Target, &m.ID, &m.HTTPSAddress, &m.ExternalAddress)
		if err != nil {
			return err
		}

		objects = append(objects, m)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"managers_members_config\" table: %w", err)
	}

	return objects, nil
}

// getManagerMemberConfigRaw can be used to run handwritten query strings to return a slice of objects.
func getManagerMemberConfigRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]ManagerMemberConfig, error) {
	objects := make([]ManagerMemberConfig, 0)

	dest := func(scan func(dest ...any) error) error {
		m := ManagerMemberConfig{}
		err := scan(&m.Target, &m.ID, &m.HTTPSAddress, &m.ExternalAddress)
		if err != nil {
			return err
		}

		objects = append(objects, m)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"managers_members_config\" table: %w", err)
	}

	return objects, nil
}

// GetManagerMemberConfig returns all available manager_member_config.
// generator: manager_member_config GetMany
func GetManagerMemberConfig(ctx context.Context, tx *sql.Tx, filters ...ManagerMemberConfigFilter) ([]ManagerMemberConfig, error) {
	var err error

	// Result slice.
	objects := make([]ManagerMemberConfig, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = cluster.Stmt(tx, managerMemberConfigObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"managerMemberConfigObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.Target != nil {
			args = append(args, []any{filter.Target}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, managerMemberConfigObjectsByTarget)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"managerMemberConfigObjectsByTarget\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(managerMemberConfigObjectsByTarget)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"managerMemberConfigObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Target == nil {
			return nil, fmt.Errorf("Cannot filter on empty ManagerMemberConfigFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getManagerMemberConfig(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getManagerMemberConfigRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"managers_members_config\" table: %w", err)
	}

	return objects, nil
}

// GetManagerMemberConfigID return the ID of the manager_member_config with the given key.
// generator: manager_member_config ID
func GetManagerMemberConfigID(ctx context.Context, tx *sql.Tx, target string) (int64, error) {
	stmt, err := cluster.Stmt(tx, managerMemberConfigID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"managerMemberConfigID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, target)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "ManagerMemberConfig not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"managers_members_config\" ID: %w", err)
	}

	return id, nil
}

// ManagerMemberConfigExists checks if a manager_member_config with the given key exists.
// generator: manager_member_config Exists
func ManagerMemberConfigExists(ctx context.Context, tx *sql.Tx, target string) (bool, error) {
	_, err := GetManagerMemberConfigID(ctx, tx, target)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateManagerMemberConfig adds a new manager_member_config to the database.
// generator: manager_member_config Create
func CreateManagerMemberConfig(ctx context.Context, tx *sql.Tx, object ManagerMemberConfig) (int64, error) {
	// Check if a manager_member_config with the same key exists.
	exists, err := ManagerMemberConfigExists(ctx, tx, object.Target)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"managers_members_config\" entry already exists")
	}

	args := make([]any, 3)

	// Populate the statement arguments.
	args[0] = object.Target
	args[1] = object.HTTPSAddress
	args[2] = object.ExternalAddress

	// Prepared statement to use.
	stmt, err := cluster.Stmt(tx, managerMemberConfigCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"managerMemberConfigCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"managers_members_config\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"managers_members_config\" entry ID: %w", err)
	}

	return id, nil
}

// DeleteManagerMemberConfig deletes the manager_member_config matching the given key parameters.
// generator: manager_member_config DeleteOne-by-Target
func DeleteManagerMemberConfig(ctx context.Context, tx *sql.Tx, target string) error {
	stmt, err := cluster.Stmt(tx, managerMemberConfigDeleteByTarget)
	if err != nil {
		return fmt.Errorf("Failed to get \"managerMemberConfigDeleteByTarget\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(target)
	if err != nil {
		return fmt.Errorf("Delete \"managers_members_config\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "ManagerMemberConfig not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d ManagerMemberConfig rows instead of 1", n)
	}

	return nil
}

// UpdateManagerMemberConfig updates the manager_member_config matching the given key parameters.
// generator: manager_member_config Update
func UpdateManagerMemberConfig(ctx context.Context, tx *sql.Tx, target string, object ManagerMemberConfig) error {
	id, err := GetManagerMemberConfigID(ctx, tx, target)
	if err != nil {
		return err
	}

	stmt, err := cluster.Stmt(tx, managerMemberConfigUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"managerMemberConfigUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.Target, object.HTTPSAddress, object.ExternalAddress, id)
	if err != nil {
		return fmt.Errorf("Update \"managers_members_config\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}
