package database

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
	"github.com/canonical/microcluster/cluster"
)

var _ = api.ServerEnvironment{}

var siteMemberStatusObjects = cluster.RegisterStmt(`
SELECT site_member_statuses.core_site_id, site_member_statuses.member_name, site_member_statuses.id, site_member_statuses.address, site_member_statuses.architecture, site_member_statuses.role, site_member_statuses.usage_cpu, site_member_statuses.usage_memory, site_member_statuses.usage_disk, site_member_statuses.status, site_member_statuses.updated_at
  FROM site_member_statuses
  ORDER BY site_member_statuses.core_site_id, site_member_statuses.member_name
`)

var siteMemberStatusObjectsByMemberName = cluster.RegisterStmt(`
SELECT site_member_statuses.core_site_id, site_member_statuses.member_name, site_member_statuses.id, site_member_statuses.address, site_member_statuses.architecture, site_member_statuses.role, site_member_statuses.usage_cpu, site_member_statuses.usage_memory, site_member_statuses.usage_disk, site_member_statuses.status, site_member_statuses.updated_at
  FROM site_member_statuses
  WHERE ( site_member_statuses.member_name = ? )
  ORDER BY site_member_statuses.core_site_id, site_member_statuses.member_name
`)

var siteMemberStatusObjectsByCoreSiteID = cluster.RegisterStmt(`
SELECT site_member_statuses.core_site_id, site_member_statuses.member_name, site_member_statuses.id, site_member_statuses.address, site_member_statuses.architecture, site_member_statuses.role, site_member_statuses.usage_cpu, site_member_statuses.usage_memory, site_member_statuses.usage_disk, site_member_statuses.status, site_member_statuses.updated_at
  FROM site_member_statuses
  WHERE ( site_member_statuses.core_site_id = ? )
  ORDER BY site_member_statuses.core_site_id, site_member_statuses.member_name
`)

var siteMemberStatusObjectsByMemberNameAndCoreSiteID = cluster.RegisterStmt(`
SELECT site_member_statuses.core_site_id, site_member_statuses.member_name, site_member_statuses.id, site_member_statuses.address, site_member_statuses.architecture, site_member_statuses.role, site_member_statuses.usage_cpu, site_member_statuses.usage_memory, site_member_statuses.usage_disk, site_member_statuses.status, site_member_statuses.updated_at
  FROM site_member_statuses
  WHERE ( site_member_statuses.member_name = ? AND site_member_statuses.core_site_id = ? )
  ORDER BY site_member_statuses.core_site_id, site_member_statuses.member_name
`)

var siteMemberStatusID = cluster.RegisterStmt(`
SELECT site_member_statuses.id FROM site_member_statuses
  WHERE site_member_statuses.core_site_id = ? AND site_member_statuses.member_name = ?
`)

var siteMemberStatusCreate = cluster.RegisterStmt(`
INSERT INTO site_member_statuses (core_site_id, member_name, address, architecture, role, usage_cpu, usage_memory, usage_disk, status, updated_at)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`)

var siteMemberStatusDeleteByMemberName = cluster.RegisterStmt(`
DELETE FROM site_member_statuses WHERE member_name = ?
`)

var siteMemberStatusDeleteByMemberNameAndCoreSiteID = cluster.RegisterStmt(`
DELETE FROM site_member_statuses WHERE member_name = ? AND core_site_id = ?
`)

var siteMemberStatusUpdate = cluster.RegisterStmt(`
UPDATE site_member_statuses
  SET core_site_id = ?, member_name = ?, address = ?, architecture = ?, role = ?, usage_cpu = ?, usage_memory = ?, usage_disk = ?, status = ?, updated_at = ?
 WHERE id = ?
`)

// siteMemberStatusColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the SiteMemberStatus entity.
func siteMemberStatusColumns() string {
	return "sites_members_status.core_site_id, sites_members_status.member_name, sites_members_status.id, sites_members_status.address, sites_members_status.architecture, sites_members_status.role, sites_members_status.usage_cpu, sites_members_status.usage_memory, sites_members_status.usage_disk, sites_members_status.status, sites_members_status.updated_at"
}

// getSiteMemberStatus can be used to run handwritten sql.Stmts to return a slice of objects.
func getSiteMemberStatus(ctx context.Context, stmt *sql.Stmt, args ...any) ([]SiteMemberStatus, error) {
	objects := make([]SiteMemberStatus, 0)

	dest := func(scan func(dest ...any) error) error {
		s := SiteMemberStatus{}
		err := scan(&s.CoreSiteID, &s.MemberName, &s.ID, &s.Address, &s.Architecture, &s.Role, &s.UsageCPU, &s.UsageMemory, &s.UsageDisk, &s.Status, &s.UpdatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, s)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"sites_members_status\" table: %w", err)
	}

	return objects, nil
}

// getSiteMemberStatusRaw can be used to run handwritten query strings to return a slice of objects.
func getSiteMemberStatusRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]SiteMemberStatus, error) {
	objects := make([]SiteMemberStatus, 0)

	dest := func(scan func(dest ...any) error) error {
		s := SiteMemberStatus{}
		err := scan(&s.CoreSiteID, &s.MemberName, &s.ID, &s.Address, &s.Architecture, &s.Role, &s.UsageCPU, &s.UsageMemory, &s.UsageDisk, &s.Status, &s.UpdatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, s)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"sites_members_status\" table: %w", err)
	}

	return objects, nil
}

// GetSiteMemberStatus returns all available site_member_status.
// generator: site_member_status GetMany
func GetSiteMemberStatus(ctx context.Context, tx *sql.Tx, filters ...SiteMemberStatusFilter) ([]SiteMemberStatus, error) {
	var err error

	// Result slice.
	objects := make([]SiteMemberStatus, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = cluster.Stmt(tx, siteMemberStatusObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"siteMemberStatusObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.MemberName != nil && filter.CoreSiteID != nil {
			args = append(args, []any{filter.MemberName, filter.CoreSiteID}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, siteMemberStatusObjectsByMemberNameAndCoreSiteID)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"siteMemberStatusObjectsByMemberNameAndCoreSiteID\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(siteMemberStatusObjectsByMemberNameAndCoreSiteID)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"siteMemberStatusObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.MemberName != nil && filter.CoreSiteID == nil {
			args = append(args, []any{filter.MemberName}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, siteMemberStatusObjectsByMemberName)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"siteMemberStatusObjectsByMemberName\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(siteMemberStatusObjectsByMemberName)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"siteMemberStatusObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.CoreSiteID != nil && filter.MemberName == nil {
			args = append(args, []any{filter.CoreSiteID}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, siteMemberStatusObjectsByCoreSiteID)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"siteMemberStatusObjectsByCoreSiteID\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(siteMemberStatusObjectsByCoreSiteID)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"siteMemberStatusObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.MemberName == nil && filter.CoreSiteID == nil {
			return nil, fmt.Errorf("Cannot filter on empty SiteMemberStatusFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getSiteMemberStatus(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getSiteMemberStatusRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"sites_members_status\" table: %w", err)
	}

	return objects, nil
}

// GetSiteMemberStatusID return the ID of the site_member_status with the given key.
// generator: site_member_status ID
func GetSiteMemberStatusID(ctx context.Context, tx *sql.Tx, coreSiteID int, memberName string) (int64, error) {
	stmt, err := cluster.Stmt(tx, siteMemberStatusID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"siteMemberStatusID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, coreSiteID, memberName)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "SiteMemberStatus not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"sites_members_status\" ID: %w", err)
	}

	return id, nil
}

// SiteMemberStatusExists checks if a site_member_status with the given key exists.
// generator: site_member_status Exists
func SiteMemberStatusExists(ctx context.Context, tx *sql.Tx, coreSiteID int, memberName string) (bool, error) {
	_, err := GetSiteMemberStatusID(ctx, tx, coreSiteID, memberName)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateSiteMemberStatus adds a new site_member_status to the database.
// generator: site_member_status Create
func CreateSiteMemberStatus(ctx context.Context, tx *sql.Tx, object SiteMemberStatus) (int64, error) {
	// Check if a site_member_status with the same key exists.
	exists, err := SiteMemberStatusExists(ctx, tx, object.CoreSiteID, object.MemberName)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"sites_members_status\" entry already exists")
	}

	args := make([]any, 10)

	// Populate the statement arguments.
	args[0] = object.CoreSiteID
	args[1] = object.MemberName
	args[2] = object.Address
	args[3] = object.Architecture
	args[4] = object.Role
	args[5] = object.UsageCPU
	args[6] = object.UsageMemory
	args[7] = object.UsageDisk
	args[8] = object.Status
	args[9] = object.UpdatedAt

	// Prepared statement to use.
	stmt, err := cluster.Stmt(tx, siteMemberStatusCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"siteMemberStatusCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"sites_members_status\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"sites_members_status\" entry ID: %w", err)
	}

	return id, nil
}

// DeleteSiteMemberStatus deletes the site_member_status matching the given key parameters.
// generator: site_member_status DeleteOne-by-MemberName-and-CoreSiteID
func DeleteSiteMemberStatus(ctx context.Context, tx *sql.Tx, memberName string, coreSiteID int) error {
	stmt, err := cluster.Stmt(tx, siteMemberStatusDeleteByMemberNameAndCoreSiteID)
	if err != nil {
		return fmt.Errorf("Failed to get \"siteMemberStatusDeleteByMemberNameAndCoreSiteID\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(memberName, coreSiteID)
	if err != nil {
		return fmt.Errorf("Delete \"sites_members_status\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "SiteMemberStatus not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d SiteMemberStatus rows instead of 1", n)
	}

	return nil
}

// UpdateSiteMemberStatus updates the site_member_status matching the given key parameters.
// generator: site_member_status Update
func UpdateSiteMemberStatus(ctx context.Context, tx *sql.Tx, coreSiteID int, memberName string, object SiteMemberStatus) error {
	id, err := GetSiteMemberStatusID(ctx, tx, coreSiteID, memberName)
	if err != nil {
		return err
	}

	stmt, err := cluster.Stmt(tx, siteMemberStatusUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"siteMemberStatusUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.CoreSiteID, object.MemberName, object.Address, object.Architecture, object.Role, object.UsageCPU, object.UsageMemory, object.UsageDisk, object.Status, object.UpdatedAt, id)
	if err != nil {
		return fmt.Errorf("Update \"sites_members_status\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}
