apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/config
- ../base/db
- ../base/management
- ../base/control

patches:
- path: ./config/dev-config.yaml
- path: ./db/dev-db-pv.yaml
- path: ./db/dev-db-pvc.yaml
- path: ./management/dev-cm-depl.yaml
- path: ./management/dev-cm-svc.yaml
- path: ./control/dev-cc-depl.yaml
