name: PR checks
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commits:
    permissions:
      pull-requests: read   # to get list of commits from the PR
    name: Canonical CLA signed and Signed-off-by (DCO)
    runs-on: ubuntu-latest
    steps:
    - name: Check if CLA signed
      uses: canonical/has-signed-canonical-cla@v1
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check that all commits are signed-off
      uses: tim-actions/dco@master
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}

  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Install dependencies
        run: |
          set -eux
          sudo add-apt-repository ppa:dqlite/dev -y --no-update
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            libdqlite-dev \
            shellcheck
          cd ui && yarn install --immutable

      - name: Build project
        run: make

      - name: Run static analysis
        run: |
          set -eux
          make check-static

  ui-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd ui && yarn install --immutable

      - name: Lint scss
        run: cd ui && yarn lint-scss

      - name: Lint JS
        run: cd ui && yarn lint-js
