name: TICS code scan
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: tics
  cancel-in-progress: false

jobs:
  tics-scan:
    name: TICS scan
    if: ${{ github.repository_owner == 'canonical' }}
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Dotrun
        run: sudo pip3 install dotrun

      - name: Install Node for frontend dependencies
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24

      - name: Install frontend dependencies
        run: cd ui && yarn install --immutable

      - name: Install Go for backend dependencies
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: 1.25.x

      - name: Install backend dependencies
        run: go mod download

      - name: Run tests with coverage
        run: scripts/run-coverage.sh

      - name: Upload coverage data
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage
          path: scripts/coverage
          retention-days: 1

      - name: Install TICS dependencies
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@b8ec13ce4d00445d75da053c47498e6f9ec5d7d6 # v0.6.1
          go install github.com/boumenot/gocover-cobertura@b1bccd90304174121462cb67f5f9e8fc496ee828 # v1.4.0

      - name: Produce TICS report
        uses: tiobe/tics-github-action@7901970b6e31982ab7c88b61ee28cac29b750395 # v3.9.0
        with:
          mode: qserver
          project: microcloud-cluster-manager
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
